# Generated by Django 2.0.5 on 2018-05-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('middle_init', models.CharField(blank=True, default='', max_length=1)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('position', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='role',
            field=models.ForeignKey(on_delete='PROTECT', related_name='officers', to='officers.Role'),
        ),
    ]
