# Generated by Django 2.0.2 on 2018-05-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='practice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='specialty',
        ),
        migrations.AddField(
            model_name='practice',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='practice',
            name='state',
            field=models.CharField(default='IL', max_length=25),
        ),
        migrations.AddField(
            model_name='practice',
            name='zip_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='doctor',
            name='practice',
            field=models.ForeignKey(on_delete='CASCADE', related_name='doctors', to='boards.Practice'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete='CASCADE', related_name='doctors', to='boards.Specialty'),
        ),
    ]
