# Generated by Django 2.0.5 on 2018-05-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180517_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_init',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='practice',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='practice',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
