# Generated by Django 2.0.2 on 2018-05-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180517_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='middle_init',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='practice',
            name='address',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='state',
            field=models.CharField(default='IL', max_length=2),
        ),
        migrations.AlterField(
            model_name='practice',
            name='website',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
