# Generated by Django 2.0.2 on 2018-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20180519_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
