# Generated by Django 2.0.5 on 2018-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(max_length=4000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('post_img', models.FileField(blank=True, upload_to='media')),
            ],
        ),
    ]
