# Generated by Django 2.0.5 on 2018-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
