# Generated by Django 2.0.5 on 2018-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180527_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='post_img',
        ),
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
