# Generated by Django 2.0.5 on 2018-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180527_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='img',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
