# Generated by Django 2.0.5 on 2018-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_announcement_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
