# Generated by Django 2.0.2 on 2018-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('date_of', models.DateField()),
                ('time_of', models.TimeField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
