# Generated by Django 2.0 on 2018-05-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180519_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
