# Generated by Django 2.0 on 2018-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180519_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('num_guests', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('event', models.ForeignKey(on_delete='PROTECT', related_name='RSVPs', to='events.Event')),
            ],
        ),
    ]
