# Generated by Django 2.0.2 on 2018-05-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180519_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='num_guests',
            new_name='guests',
        ),
    ]
