# Generated by Django 2.0.2 on 2018-05-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180523_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
    ]
