# Generated by Django 2.0.2 on 2018-05-23 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180523_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
