# Generated by Django 2.0.2 on 2018-05-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180530_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
