# Generated by Django 2.0.5 on 2018-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20180521_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='year',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='', max_length=4),
        ),
    ]
