# Generated by Django 2.0.5 on 2018-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20180521_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='pdf_img',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
