# Generated by Django 2.0.5 on 2018-05-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_auto_20180521_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='pdf_img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
