# Generated by Django 2.0.5 on 2018-05-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_auto_20180521_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='pdf_img',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
