# Generated by Django 2.0.5 on 2018-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_auto_20180604_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
    ]
